# Generated by Django 3.2.9 on 2021-11-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
        migrations.RenameModel(
            old_name='ReservationsChoices',
            new_name='ReservationsChoice',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
